POST http://localhost:8080/users/signup HTTP/1.1
content-type: application/json

{
    "name":"Devendra",
    "username":"devendra.b",
    "email":"devendrab.official@gmail.com",
    "password":"password",
    "profile_url":"https://github.com/devendrab-official/profile"
}

###
POST http://localhost:8080/users/login HTTP/1.1
content-Type: application/json

{
    "email":"devendrab.official@gmail.com",
    "password":"password"
}